"""criar tabela clientes

Revision ID: f65cc1642801
Revises: 
Create Date: 2026-09-26 21:37:58.836289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65cc1642801'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
